// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task.Models;

#nullable disable

namespace Task.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task.Models.Routes", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Code");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Task.Models.Sample", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Code");

                    b.ToTable("samples");
                });

            modelBuilder.Entity("Task.Models.SamplesRoutes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdRoute")
                        .HasColumnType("int");

                    b.Property<int>("IdSample")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdRoute");

                    b.HasIndex("IdSample");

                    b.ToTable("samplesRoutes");
                });

            modelBuilder.Entity("Task.Models.SamplesRoutes", b =>
                {
                    b.HasOne("Task.Models.Routes", "route")
                        .WithMany("samplesRoutes")
                        .HasForeignKey("IdRoute")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task.Models.Sample", "sample")
                        .WithMany("samplesRoutes")
                        .HasForeignKey("IdSample")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("route");

                    b.Navigation("sample");
                });

            modelBuilder.Entity("Task.Models.Routes", b =>
                {
                    b.Navigation("samplesRoutes");
                });

            modelBuilder.Entity("Task.Models.Sample", b =>
                {
                    b.Navigation("samplesRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
